name = "server-utils"
author = "Letis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "014f694e2cd3f86f748c8cb2186315e2bafcbb05553f79fe949aec734f61ecba"

[versions]
minecraft = "1.21.4"
quilt = "0.28.1-beta.1"
